- src/commands/$default.ts
- src/commands/tools.ts
- src/core/executeToolCall.ts
- src/core/toolAgent.test.ts
- src/core/toolAgent.ts
- src/index.ts
- src/tools/getTools.test.ts
- src/tools/interaction/subAgent.test.ts
- src/tools/interaction/subAgent.ts
- src/tools/io/fetch.ts
- src/tools/io/readFile.test.ts
- src/tools/io/readFile.ts
- src/tools/io/updateFile.test.ts
- src/tools/io/updateFile.ts
- src/tools/system/shellExecute.test.ts
- src/tools/system/shellExecute.ts
- src/utils/logger.test.ts
- src/utils/logger.ts
- src/utils/versionCheck.test.ts
- src/utils/versionCheck.ts
> Check for updates

- src/tools/system/shellMessage.test.ts
- src/tools/system/shellStart.test.ts
- src/tools/system/shellStart.ts
> combine sync and async shell modes into one.

- .vscode/extensions.json
- .vscode/settings.json
- docs/LargeCodeBase_Plan.md
- docs/comparisons/mycoder-vs-aider.md
- docs/comparisons/mycoder-vs-claude-code.md
- docs/comparisons/mycoder-vs-codebuff.md
> Comparisons

- .husky/pre-commit
- CONTRIBUTING.md
- package.json
- pnpm-lock.yaml
Implements issue #66 by adding pre-commit hooks using husky and lint-staged. This ensures code quality and consistency by automatically running lint and format commands before each commit.
> Add pre-commit hooks for lint and format commands

- docs/comparisons/github-copilot-cli-analysis.md
- docs/comparisons/tabby-analysis.md
This PR adds analyses for two additional AI coding tools as requested:\n\n1. **Tabby** - A self-hosted AI coding assistant built with Rust (addresses #73)\n2. **GitHub Copilot CLI** - A terminal-based AI assistant for shell commands (addresses #74)\n\nThese analyses follow the same format as the other tool analyses, focusing on each tool's features, strengths, and limitations rather than direct comparisons.\n\nPart of the effort to expand our documentation with analyses of various AI coding tools.
> Add analyses for Tabby and GitHub Copilot CLI

- .changeset/github-mode.md
- .changeset/text-editor.md
- README.md
- docs/github-mode.md
- packages/agent/src/core/toolAgent/config.ts
- packages/cli/README.md
- packages/cli/src/commands/.ts
- packages/cli/src/commands/config.ts
- packages/cli/tests/commands/config.test.ts
- packages/cli/tests/settings/config.test.ts
Implements GitHub mode for MyCoder that enables the agent to work with GitHub issues and PRs as its primary workflow.
When enabled, the agent will:
- Start from existing GitHub issues or create new ones for tasks
- Create branches for issues it's working on
- Make commits with descriptive messages
- Create PRs when work is complete
- Create additional GitHub issues for follow-up tasks or ideas
Changes include:
- Added GitHub mode detection in the system prompt
- Updated documentation in README.md and CLI README.md
- Added dedicated documentation in docs/github-mode.md
- Created a changeset for version tracking
Closes #67
> Add GitHub mode to MyCoder for working with issues and PRs

- .changeset/openai-models.md
- packages/agent/src/core/toolAgent/config.ts
- packages/agent/src/index.ts
- packages/agent/src/tools/interaction/subAgent.ts
- packages/cli/src/commands/$default.ts
- packages/cli/src/options.ts
- packages/cli/src/settings/config.ts
- packages/cli/tests/settings/config.test.ts
> Add support for OpenAI models (o3 mini and GPT-4o)

- packages/agent/src/core/toolAgent/config.ts
- packages/agent/src/tools/interaction/subAgent.ts
- packages/cli/README.md
- packages/cli/src/commands/$default.ts
- packages/cli/src/settings/config.ts
- packages/cli/tests/settings/config.test.ts
Closes #85
This PR adds support for Ollama models via the Vercel AI SDK.
> Add Ollama support via the Vercel AI SDK

- packages/agent/package.json
- packages/agent/src/core/toolAgent/config.test.ts
- packages/agent/src/core/toolAgent/config.ts
- packages/cli/README.md
- packages/cli/src/commands/$default.ts
- packages/cli/src/options.ts
- pnpm-lock.yaml
This PR adds support for two new AI providers:
1. xAI/Grok via the Vercel AI SDK provider (@ai-sdk/xai)
2. Mistral AI via the Vercel AI SDK provider (@ai-sdk/mistral)
- Added dependencies for xAI and Mistral AI providers
- Updated `ModelProvider` type to include 'xai' and 'mistral'
- Updated `getModel()` function to support the new providers
- Added API key checks for xAI and Mistral AI (XAI_API_KEY and MISTRAL_API_KEY)
- Updated CLI options to include the new providers
- Updated README.md with instructions for the new providers
- Added tests for the new providers
- Added unit tests for the new providers
- Verified all existing tests pass
- xAI Provider: https://sdk.vercel.ai/providers/ai-sdk-providers/xai
- Mistral Provider: https://sdk.vercel.ai/providers/ai-sdk-providers/mistral
Closes …
> Add xAI/Grok and Mistral AI support via Vercel AI SDK

- packages/cli/tests/settings/config-defaults.test.ts
- packages/cli/tests/settings/configDefaults.test.ts
The test was failing with "Cannot read properties of undefined (reading 'version')" because it was trying to mock the package.json import, which doesn't work well with ES Modules.
Changes made:
1. Rewrote the test to focus specifically on testing the config defaults functionality
2. Created direct tests for the behavior we care about:
- Config values are used as defaults when command line arguments are not provided
- Command line arguments override config values when they are provided
3. Added tests that verify the actual toolAgent call receives the correct parameters
This completes the implementation of GitHub issue #77 to add config defaults for headless, userSession, and pageFilter options.
Closes #77
> Fix test issues for configDefaults.test.ts

- packages/cli/tests/settings/config.test.ts
This PR fixes the failing tests in the CLI package after the implementation of the customPrompt configuration option in PR #96. 
- Updated test expectations in `config.test.ts` to include the new `customPrompt` field that was added to the default configuration
- Verified that all tests now pass in the CLI package
Fixes tests after PR #96 (Issue #95)
> Fix config tests to include customPrompt field

- packages/agent/src/core/toolAgent/config.ts
This PR replaces Unix/Linux-specific shell commands with Node.js native APIs for gathering system information in the agent prompt. This ensures compatibility across all operating systems, including Windows.
- Replaced `execSync('pwd')` with `process.cwd()`
- Replaced `execSync('ls -la')` with `fs.readdirSync()` and formatting logic
- Replaced `execSync('uname -a')` with `os` module functions
- Kept `new Date().toString()` which was already cross-platform
- All tests pass
- The output format is preserved to maintain compatibility with existing code
- Added proper error handling for each function
- Works consistently on Windows, macOS, and Linux
- Removes dependency on external shell commands
- Provides more reliable system information
Fixes #98
> Replace shell commands with Node.js APIs for cross-platform compatibility

- packages/cli/src/index.ts
- packages/cli/src/utils/performance.ts
- packages/cli/tests/settings/config.test.ts
This PR fixes an issue in PR #101 where yargs was being initialized twice in the main function. This double initialization was done to check for the profiling flag early, but it's inefficient and could cause problems.
1. Modified the `performance.ts` module to always collect timing data regardless of whether profiling is enabled
- Only the reporting of the data is conditional on the profiling flag
- This allows us to collect all timing data without needing to know if profiling is enabled upfront
2. Removed the early yargs initialization in the main function
- Now we only initialize yargs once
- The profiling flag is checked after yargs has been properly initialized
3. Updated tests to reflect the changes
Fixes part of #100 (CLI startup performance issues)
Should be merged into PR #101
All …
> Fix double yargs initialization in CLI profiling feature

- packages/cli/README.md
- packages/cli/src/commands/test-profile.ts
- packages/cli/src/index.ts
- packages/cli/src/options.ts
- packages/cli/src/settings/config.ts
- packages/cli/src/utils/performance.ts
- packages/cli/tests/settings/config.test.ts
This PR adds a profiling feature to the CLI to help diagnose the slow startup times on Windows compared to MacOS (Issue #100).
1. Added a `--profile` flag to enable performance profiling
2. Created a performance tracking module that:
- Measures timing of key initialization steps
- Reports detailed timing information
- Provides platform-specific diagnostics on Windows
3. Added a `test-profile` command to easily test the profiling feature
4. Optimized Sentry initialization to only run when needed
Run any command with the `--profile` flag to see timing information:
```bash
mycoder --profile --help
mycoder --profile test-profile
```
The profiling output shows:
- Timing for each initialization step
- Total startup time
- On Windows: additional platform diagnostics to help identify bottlenecks …
> Add CLI startup profiling feature

- .changeset/convert-to-zod.md
- .changeset/github-mode.md
- .changeset/implement-token-caching.md
- .changeset/openai-models.md
- .changeset/performance-profiling.md
- .changeset/refactor-tool-agent.md
- .changeset/text-editor.md
- .changeset/windows-compatibility.md
- packages/agent/CHANGELOG.md
- packages/agent/package.json
- packages/agent/src/tools/browser/browseMessage.ts
- packages/agent/src/tools/browser/browseStart.ts
- packages/agent/src/tools/interaction/subAgent.ts
- packages/agent/src/tools/system/shellExecute.ts
- packages/agent/src/tools/system/shellMessage.ts
- packages/agent/src/tools/system/shellStart.ts
- packages/cli/CHANGELOG.md
- packages/cli/package.json
This PR addresses issue #109 by improving the tool parameter schemas in several components:
1. Removed `.max(80)` constraint from description fields in multiple tools:
- browseStart.ts
- subAgent.ts
- shellExecute.ts
- shellMessage.ts
- shellStart.ts
2. Significant restructuring of parameter schema in browseMessage.ts:
- Flattened the nested action object structure
- Moved actionType and related fields to the top level
- Simplified parameter validation logic
- Improved error handling for invalid parameters
- Cleaner API for tool interactions
- More consistent parameter structure across tools
- Improved developer experience
- Better error messages when parameters are invalid
All tests are passing with these changes, confirming backward compatibility while improving the code structure.
The …
> Refactor Tool Parameter Schemas

- packages/agent/src/core/toolAgent/toolAgentCore.ts
- packages/agent/src/utils/errors.ts
- packages/cli/src/commands/$default.ts
This PR fixes a bug where the CLI tool would throw an error about the Anthropic API key not being set, even when using other LLM providers. The issue was caused by a hardcoded check for the Anthropic API key in the tool agent implementation that ran regardless of which provider was configured.
1. Removed the hardcoded Anthropic API key check from `toolAgentCore.ts`
2. Created a provider configuration map with API key names and documentation URLs
3. Implemented a generic `getProviderApiKeyError` function that generates provider-specific error messages
4. Updated the CLI command to use the provider config map for API key validation
5. Maintained backward compatibility by keeping the `getAnthropicApiKeyError` function
- **Maintainability**: Adding a new provider only requires adding an entry …
> Fix #115: Remove hardcoded Anthropic API key check

- .changeset/itchy-hounds-cross.md
- packages/agent/src/core/tokens.ts
- packages/agent/src/core/toolAgent/toolAgentCore.ts
- packages/agent/src/core/types.ts
- packages/cli/README.md
- packages/cli/src/commands/$default.ts
- packages/cli/src/options.ts
- packages/cli/src/settings/config.ts
- packages/cli/tests/settings/config.test.ts
This PR adds a new configuration option called `tokenCache` to control whether token caching is enabled in API calls. The default value is `true` to maintain current behavior.
When set to `false`, the CLI bypasses adding cache-control metadata to messages when calling the LLM API.
- Added `tokenCache: boolean` to the configuration schema with a default value of `true`
- Modified the `ToolContext` type to include the `tokenCache` option
- Added the `tokenCache` property to the `TokenTracker` class
- Modified `toolAgentCore.ts` to conditionally apply cache control based on this setting
- Added a command-line option for `tokenCache`
- Updated the README to document the new option
The implementation has been tested by:
- Setting the configuration via `mycoder config set tokenCache false`
- …
> Add tokenCache configuration option

- .husky/pre-commit
- CONTRIBUTING.md
This PR enhances the pre-commit hooks to include build and test checks, preventing commits that would break the build or fail tests.
- Updated the pre-commit hook to run `pnpm build` and `pnpm test` before allowing commits
- Updated the CONTRIBUTING.md documentation to reflect these changes
- Tested the pre-commit hook locally to ensure it correctly prevents commits when builds fail or tests don't pass
- Confirmed that the hook allows commits when all checks pass
Fixes #122
There's a Husky deprecation warning about the shebang and source line that will need to be addressed in a future update when upgrading to Husky v10.0.0.
> Add build and test checks to pre-commit hooks

- packages/cli/README.md
- packages/cli/src/commands/config.ts
- packages/cli/src/settings/config.ts
- packages/cli/tests/commands/config.test.ts
This PR implements the enhancements requested in issue #117 for the CLI config command:
1. Added a new `clear` subcommand that allows users to reset a specific configuration option to its default value
2. Enhanced the `list` command to indicate which configuration options are using default values
- New `clear` subcommand to reset configuration options to defaults
- Added `getDefaultConfig()` function to access default configuration values
- Added visual indicators in the `list` command output to distinguish between default and custom values
- CLI README.md to document the new `clear` command
- Added tests for the new functionality
```bash
mycoder config clear customPrompt
mycoder config list
```
- Manual testing performed to verify the new functionality works as expected
- Added unit …
> Enhance CLI Config Command with 'clear' Option and Default Value Indicators

- packages/cli/README.md
- packages/cli/src/commands/config.ts
- packages/cli/src/settings/config.ts
- packages/cli/tests/commands/config.test.ts
This PR adds additional improvements to the config command implementation from PR #124:
1. **Validation for Set Command**: The `set` command now validates that the provided key exists in the default configuration, preventing users from setting invalid configuration keys.
2. **Filtering for List Command**: The `list` command now filters out any configuration keys that are not part of the default configuration, ensuring only valid keys are displayed.
- Validation in the `set` command to check if the key exists in default config
- Filtering in the `list` command to only show valid configuration keys
- Tests for the new validation and filtering functionality
- Added unit tests for the new validation and filtering functionality
- Manual testing performed to verify correct behavior
This PR …
> Add validation for config keys and filter list output

- packages/agent/src/core/toolAgent/toolAgentCore.test.ts
- packages/agent/src/core/toolAgent/toolAgentCore.ts
This PR fixes an issue where the agent incorrectly identifies a response as empty when it contains tool calls but no text content. The agent was unnecessarily "scolding" the LLM in these cases, even though the LLM was functioning correctly.
- Modified the empty response detection logic in `toolAgentCore.ts` to check for both the absence of text content AND the absence of tool calls before considering a response truly empty
- Added a test to verify the fix
- Added a unit test that verifies the condition includes both checks
- All existing tests pass
Fixes #127
> Fix: Only consider response empty if no text AND no tool calls

- packages/cli/src/commands/config.ts
- packages/cli/src/settings/config.ts
This PR implements the functionality requested in issue #133, allowing users to clear all configuration settings at once.
- Added a new `clearAllConfig()` function in `config.ts` that removes the config file
- Extended the `config clear` command to accept a new `--all` flag
- Added a confirmation prompt before clearing all settings
- Updated help text and examples to document the new option
- Manually tested the new `mycoder config clear --all` command
- Verified that the confirmation prompt works correctly
- Confirmed that all settings are reset to defaults after clearing
Fixes #133
> Add ability to clear all configuration settings

- packages/cli/src/commands/$default.ts
- packages/cli/src/commands/config.ts
- packages/cli/src/settings/config.ts
- packages/cli/tests/settings/config.test.ts
This PR implements the functionality requested in issue #134, allowing users to store API keys in the configuration file as an alternative to setting environment variables.
- Added API key fields to the default configuration in `config.ts`
- Updated the API key retrieval logic in `$default.ts` to check both the config file and environment variables
- Added special handling for API keys in the config command with security warnings and confirmation
- Added example to the help text for setting API keys
- Added warnings about the security implications of storing API keys in plaintext
- Added a confirmation prompt before storing API keys
- Environment variables still take precedence over stored configuration
- Manually tested setting and using API keys from configuration
- Verified that the …
> Add ability to store API keys in configuration

- README.md
- docs/installation.md
- docs/usage.md
- packages/cli/README.md
This PR addresses issue #114 by adding comprehensive installation instructions for macOS and Linux operating systems.
- Created a new `installation.md` file in the docs directory with detailed instructions for:
- Installing Node.js using NVM (recommended approach)
- Alternative installation methods for Node.js
- Installing MyCoder
- Setting up API keys
- Installing GitHub CLI for GitHub integration
- Troubleshooting common issues on macOS and Linux
- Updated references to this new guide in:
- Main README.md
- CLI package README.md
- Usage documentation (docs/usage.md)
- Verified all links work correctly
- Ensured markdown formatting is consistent
- Confirmed instructions are clear and accurate for both macOS and Linux
Fixes #114
> docs: add detailed installation instructions for macOS and Linux

- .github/workflows/ci.yml
- .github/workflows/issue-comment.yml
- README.md
- docs/github-comment-commands.md
This PR adds a GitHub Action that responds to specific commands in GitHub issue comments:
- `/mycoder pr` - Implements a PR for the given issue
- `/mycoder plan` - Generates an implementation plan as a comment
The GitHub Action:
- Triggers on each new comment on any GitHub issue
- Checks for specific command patterns in the comment
- For `/mycoder pr`:
- Checks out the repository
- Sets up Node.js
- Installs MyCoder via `pnpm install -g mycoder`
- Runs MyCoder with `--githubMode true` to implement a PR for the issue
- For `/mycoder plan`:
- Similar setup, but instructs MyCoder to review the issue and submit an implementation plan
- Added a new documentation file `docs/github-comment-commands.md` with detailed information
- Updated the README.md to mention this new feature
This PR …
> Add GitHub Action for issue comment commands

- .changeset/enable-user-prompt-option.md
- README.md
- packages/agent/src/core/types.ts
- packages/agent/src/tools/getTools.ts
- packages/agent/src/tools/interaction/subAgent.ts
- packages/cli/src/commands/$default.ts
- packages/cli/src/options.ts
This PR adds a new command line option `--enableUserPrompt` that defaults to true but can be set to false to disable the userPrompt tool for fully automated sessions.
- Added `enableUserPrompt` option to the shared options in CLI package
- Modified getTools function to conditionally include userPrompt tool based on this setting
- Updated ToolContext type to include enableUserPrompt option
- Updated subAgent to use the new getTools API
- Updated README.md to document the new option
- Added changeset file for patch version bump
- All existing tests pass
- Manually verified that the userPrompt tool is disabled when `--enableUserPrompt false` is used
Fixes #164
> Add enableUserPrompt command line option

- README.md
- packages/cli/src/commands/$default.ts
- packages/cli/src/options.ts
This PR adds `--githubMode` and `--userPrompt` as boolean command line options that override any config settings or defaults. These CLI options are required for our GitHub Action integration to work properly.
1. Added `githubMode` to the `SharedOptions` type and `sharedOptions` object in `options.ts`
2. Added `userPrompt` as an alias for `enableUserPrompt` in `options.ts`
3. Updated the default command handler to properly use these CLI options to override config values:
- Now checking for `argv.githubMode` before falling back to `config.githubMode`
- Now checking for `argv.userPrompt` before falling back to `argv.enableUserPrompt`
4. Updated README.md to document the new CLI options
- All existing tests pass
- Manually verified that the CLI options work as expected
Closes #168
> feat: add --githubMode and --userPrompt as boolean CLI options

- CHANGELOG.md
- README.md
- packages/cli/README.md
- packages/cli/src/commands/$default.ts
- packages/cli/src/options.ts
This PR adds two new CLI options to support automated usage scenarios:
- `--userWarning=false` - Disables the user consent check
- `--upgradeCheck=false` - Disables the version upgrade check
When running MyCoder in automated environments like CI/CD pipelines:
1. The user consent prompt blocks execution and requires manual intervention
2. The version upgrade check adds unnecessary output and network calls
Added two boolean CLI options that can be set to `false` to disable these features:
- `--userWarning=false` bypasses the consent check
- `--upgradeCheck=false` skips the version check
- Added new options to `SharedOptions` type and `sharedOptions` object in `options.ts`
- Updated consent check in `.ts` to respect the `userWarning` option
- Updated version check in `.ts` to respect the …
> feat: add CLI options for automated usage scenarios

- packages/agent/src/tools/io/textEditor.test.ts
- packages/agent/src/tools/io/textEditor.ts
This change modifies the textEditor tool to allow overwriting existing files when using the 'create' command, rather than throwing an error when a file already exists. It also adds proper history tracking for undo functionality and includes tests for the new behavior.
Fixes #192
> feat: allow textEditor to overwrite existing files with create command

- CONTRIBUTING.md
- README.md
- package.json
- pnpm-lock.yaml
- Added commitizen and cz-conventional-changelog as dev dependencies
- Added 'commit' script to package.json to run commitizen
- Added commitizen configuration to package.json
- Updated CONTRIBUTING.md to include information about using commitizen
- Updated README.md to mention the pnpm commit command
Closes #189
> feat: add commitizen for interactive commit messages

- packages/agent/src/core/toolAgent.test.ts
- packages/agent/src/tools/interaction/agentMessage.ts
- packages/agent/src/tools/interaction/agentStart.ts
- packages/agent/src/tools/interaction/agentTools.test.ts
- packages/agent/src/tools/interaction/subAgent.test.ts
- packages/agent/src/tools/interaction/subAgent.ts
- packages/agent/src/tools/interaction/userPrompt.test.ts
- packages/agent/src/tools/io/textEditor.test.ts
- packages/agent/src/tools/system/respawn.test.ts
- packages/agent/src/tools/system/shellExecute.test.ts
- packages/agent/src/tools/system/shellMessage.test.ts
- packages/agent/src/tools/system/shellStart.test.ts
- packages/agent/src/tools/system/sleep.test.ts
- packages/cli/src/settings/config.ts
- packages/cli/tests/commands/config.test.ts
- packages/cli/tests/settings/config-defaults.test.ts
- packages/cli/tests/settings/config.test.ts
- packages/cli/tests/settings/configDefaults.test.ts
Quick fix to work around some bugs.
> Default GitHub mode on

- packages/agent/src/tools/io/textEditor.test.ts
- packages/agent/src/tools/io/textEditor.ts
This PR addresses issue #223 by modifying the textEditor tool to display relative paths instead of full absolute paths in log messages.
- Modified the `logParameters` function in the textEditor tool to convert absolute paths to relative paths when the path is within the working directory
- Added comprehensive tests to verify the path conversion logic
- Ensured backward compatibility by preserving absolute paths for locations outside the working directory
Before:
```
view operation on "/Users/benhouston/Coding/Business/drivecore/mycoder2/packages/agent/src/core/llm/provider.ts", Viewing provider.ts merge conflict
```
After:
```
view operation on "./packages/agent/src/core/llm/provider.ts", Viewing provider.ts merge conflict
```
Added unit tests that verify:
- Absolute paths within the …
> fix: convert absolute paths to relative paths in textEditor log output

- packages/agent/src/core/llm/provider.ts
- packages/agent/src/core/llm/providers/ollama.ts
- packages/agent/src/core/toolAgent/config.test.ts
- packages/agent/src/core/toolAgent/config.ts
- packages/agent/src/utils/errors.ts
- packages/cli/src/commands/$default.ts
- packages/cli/src/options.ts
- packages/cli/src/settings/config.ts
This PR implements Ollama support for the MyCoder LLM abstraction, addressing issue #147.
- Created a new Ollama provider implementation in `packages/agent/src/core/llm/providers/ollama.ts`
- Registered the provider in the LLM abstraction
- Added configuration options for Ollama:
- Added `ollamaBaseUrl` to CLI config (default: http://localhost:11434)
- Added CLI option for specifying Ollama endpoint
- Updated the provider selection to include Ollama
- Updated the toolAgent config to support Ollama models
- Fixed type errors and added tests
- Added tests for Ollama provider
- Ensured existing tests pass
- Manually tested with local Ollama server
Users can now use Ollama models with MyCoder:
```bash
mycoder config set provider ollama
mycoder config set model llama3
mycoder config set …
```
> Add Ollama support to LLM abstraction

- packages/cli/src/commands/$default.ts
- packages/cli/src/utils/gitCliCheck.test.ts
- packages/cli/src/utils/gitCliCheck.ts
This PR adds a new feature to check for git and gh CLI tools when GitHub mode is enabled. 
- Added a new utility function `checkGitCli()` that checks:
- If git CLI is available
- If gh CLI is available
- If gh CLI is authenticated
- Added warning messages when GitHub mode is enabled but required tools are missing
- Added unit tests for the new functionality
The implementation adds a check in the main command handler that runs when GitHub mode is enabled. If git or gh CLI tools are not available or gh is not authenticated, appropriate warning messages are displayed to the user.
This helps users understand why GitHub mode might not be working as expected and provides guidance on how to fix the issues.
Fixes #217
> Check for git and gh CLI tools when GitHub mode is enabled

- README.md
- mycoder.config.js
- packages/agent/src/core/toolAgent/config.ts
- packages/agent/src/core/types.ts
- packages/cli/src/settings/config.ts
This PR implements support for multiple line custom prompts in `mycoder.config.js` as requested in issue #249. Instead of only supporting a single line string, the `customPrompt` configuration option now accepts either a string (for backward compatibility) or an array of strings (for multiple line prompts).
- Updated `customPrompt` type in `packages/agent/src/core/types.ts` to accept `string | string[]`
- Updated `customPrompt` type in `packages/cli/src/settings/config.ts` to accept `string | string[]`
- Modified system prompt generation in `packages/agent/src/core/toolAgent/config.ts` to handle both string and array formats
- Updated examples in `mycoder.config.js` and `README.md` to demonstrate the new feature
Users can now define custom prompts in two ways:
```js
// Single line …
```
> feat: support multiple line custom prompts in mycoder.config.js

- docs/custom-commands.md
- mycoder.config.js
- packages/cli/src/commands/$default.ts
- packages/cli/src/commands/custom.ts
- packages/cli/src/index.ts
- packages/cli/src/settings/config.ts
This PR implements the custom CLI commands feature requested in issue #251. It allows users to define custom commands in their `mycoder.config.js` file.
- Define custom CLI commands in `mycoder.config.js`
- Commands can have required and optional arguments
- Commands execute JavaScript functions that return prompts
- Documentation added in `docs/custom-commands.md`
- Example configuration in `mycoder.config.js` (commented out)
- Extended the `Config` type to include custom commands
- Created a custom command handler in `packages/cli/src/commands/custom.ts`
- Refactored the default command handler for reuse
- Added validation for custom commands
- Updated the main index.ts to register custom commands
```js
// mycoder.config.js
export default {
// ... other config options
// Custom commands …
```
> Add custom CLI commands feature

- packages/cli/package.json
- packages/cli/src/settings/config.ts
This PR replaces cosmiconfig with c12 for better TypeScript support and additional configuration features, as requested in issue #260.
- Replaced cosmiconfig with c12 for configuration loading
- Added configuration watching capability via `watchConfigForChanges` function
- Removed dependency on cosmiconfig
- Maintained backward compatibility with existing configuration files
- Fixed type issues when working with c12's configuration types
1. **TypeScript Support**: c12 has built-in TypeScript support without requiring custom loaders
2. **More Configuration Formats**: Supports JSONC, JSON5, TOML in addition to standard formats
3. **Configuration Directory**: Supports a `.config/` directory for organizing configuration files
4. **Environment-specific Configurations**: Allows for …
> feat: replace cosmiconfig with c12 for configuration management

- README.md
- packages/docs/docs/providers/index.mdx
- packages/docs/docs/providers/local-openai.md
- packages/docs/docs/providers/ollama.md
- packages/docs/docs/providers/xai.md
This PR adds documentation for the new providers added in PR #273 (gpustack/local-openai and xai) and updates references from ollamaBaseUrl to baseUrl.
1. Added new provider documentation:
- `local-openai.md` for GPUStack and other OpenAI-compatible servers
- `xai.md` for Grok models from xAI
2. Updated references from ollamaBaseUrl to baseUrl in:
- Ollama provider documentation
- README.md
3. Updated the providers index.mdx to include the new providers
Documentation has been built and verified locally.
Fixes #278
> docs: add documentation for new providers and update baseUrl references

- .github/workflows/ci.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/issue-comment.yml
- .github/workflows/release.yml
- packages/docs/Dockerfile
- packages/docs/package.json
Upgrade pnpm, GitHub checkout, node actions.
> Upgrade ci actions

- README.md
- packages/docs/docs/usage/configuration.md
This PR adds documentation about alternative configuration file locations supported by MyCoder through the c12 library, as requested in issue #298.
The documentation now includes information about:
- `.mycoder.config.js` in project root (dot-prefixed config file)
- `.config/mycoder.js` in project root (config directory)
- `.mycoder.rc` files (RC config files)
- `~/.config/mycoder/config.js` (XDG standard user configuration)
These changes were made to both:
1. The main README.md file
2. The detailed configuration documentation in packages/docs/docs/usage/configuration.md
Resolves #298
> docs: add alternative configuration file locations to documentation

- packages/agent/src/core/backgroundTools.cleanup.test.ts
- packages/agent/src/core/backgroundTools.test.ts
- packages/agent/src/core/backgroundTools.ts
- packages/agent/src/index.ts
- packages/agent/src/tools/getTools.ts
- packages/agent/src/tools/system/ShellTracker.test.ts
- packages/agent/src/tools/system/ShellTracker.ts
- packages/agent/src/tools/system/listBackgroundTools.ts
- packages/agent/src/tools/system/listShells.test.ts
- packages/agent/src/tools/system/listShells.ts
- packages/agent/src/tools/system/shellMessage.test.ts
- packages/agent/src/tools/system/shellMessage.ts
- packages/agent/src/tools/system/shellStart.test.ts
- packages/agent/src/tools/system/shellStart.ts
- packages/cli/src/utils/cleanup.ts
This PR implements a dedicated `ShellTracker` class to handle shell process tracking, decoupling it from the general `backgroundTools` implementation. This change improves modularity and separation of concerns.
- Created a new `ShellTracker` class with methods for tracking shell processes
- Implemented a new `listShells` tool to list shell processes
- Updated `shellStart` and `shellMessage` to use the new `ShellTracker` instead of `backgroundTools`
- Modified `backgroundTools` to remove shell-specific functionality and use `ShellTracker` for cleanup
- Updated `listBackgroundTools` to exclude shell processes (now handled by `listShells`)
- Added tests for the new `ShellTracker` class and `listShells` tool
- Updated existing tests to work with the new structure
All tests are passing. The …
> feat: implement ShellTracker to decouple from backgroundTools

- packages/agent/src/core/backgroundTools.cleanup.test.ts
- packages/agent/src/core/backgroundTools.ts
- packages/agent/src/tools/getTools.ts
- packages/agent/src/tools/interaction/agentStart.ts
- packages/agent/src/tools/interaction/agentTracker.ts
- packages/agent/src/tools/system/listAgents.ts
This PR implements the decoupling of agent tracking from backgroundTools by creating a dedicated AgentTracker class. The implementation follows the technical details provided in issue #292.
- Created new `AgentTracker` class in `packages/agent/src/tools/interaction/agentTracker.ts`
- Implemented new `listAgents` tool in `packages/agent/src/tools/system/listAgents.ts`
- Updated `agentStart.ts` to use the new AgentTracker
- Modified `backgroundTools.ts` to delegate agent cleanup to AgentTracker
- Updated tests to work with the new implementation
- The implementation maintains backward compatibility by continuing to register agents with backgroundTools while also using the new AgentTracker
- The AgentTracker provides a more focused API for tracking and managing agents
- The listAgents tool …
> feat: implement AgentTracker decoupling from backgroundTools

- packages/agent/src/core/toolAgent/toolAgentCore.ts
- packages/agent/src/core/types.ts
- packages/agent/src/tools/agent/AgentTracker.ts
- packages/agent/src/tools/agent/agentMessage.ts
- packages/agent/src/tools/agent/agentStart.ts
This PR adds bidirectional communication between parent agents and sub-agents through the `agentMessage` tool. Previously, parent agents could only check the output of sub-agents but couldn't communicate with them. This enhancement enables parent agents to send guidance messages to sub-agents, which are then inserted into the sub-agent's message queue.
1. Added `parentMessages` array to the `AgentState` interface to store messages from parent agents
2. Updated the `agentMessage` tool to append messages to this array when the `guidance` parameter is provided
3. Modified the `toolAgent` core to check for parent messages on each iteration and insert them into the message queue
4. Added appropriate return values to indicate if a message was sent and how many messages are in the queue
- All …
> feat: add parent-to-subagent communication in agentMessage tool

- packages/agent/README.md
- packages/docs/README.md
This PR updates the CLI README.md with comprehensive documentation about the package structure, features, and usage.
Key improvements:
- Added information about the Custom Commands feature
- Improved the structure and organization of the documentation
- Added a new section on Package Structure
- Added a Development section with instructions for building and testing
- Updated the configuration options to reflect current capabilities
- Fixed minor inconsistencies in the existing documentation
Fixes #319
The updated README has been reviewed for accuracy and completeness. All information is consistent with the current implementation of the CLI package.
This update focuses on making the CLI documentation more comprehensive and user-friendly, especially highlighting the custom commands feature …
> docs: update CLI README with comprehensive documentation

- README.md
- implementation-proposal.md
- mycoder.config.js
- packages/agent/CHANGELOG.md
- packages/agent/package.json
- packages/agent/src/tools/session/lib/BrowserDetector.ts
- packages/agent/src/tools/session/lib/SessionManager.ts
- packages/agent/src/tools/session/lib/types.ts
- packages/agent/src/tools/session/sessionStart.ts
- packages/cli/CHANGELOG.md
- packages/cli/package.json
This PR adds system browser detection for Playwright integration in mycoder. It allows mycoder to detect and use system-installed browsers instead of requiring Playwright's bundled browsers to be installed separately. This is particularly useful when mycoder is installed globally via npm.
- Add `BrowserDetector` module for cross-platform browser detection (Windows, macOS, Linux)
- Update `SessionManager` to use detected system browsers via Playwright's `executablePath` option
- Add configuration options in `mycoder.config.js` for browser preferences
- Update documentation in README.md with information about the browser detection feature
- Maintain compatibility with headless mode and clean sessions
The implementation has been tested with:
- Browser detection on macOS
- Proper fallback to …
> feat(browser): add system browser detection for Playwright

- packages/agent/CHANGELOG.md
- packages/agent/package.json
- packages/agent/src/core/llm/providers/anthropic.ts
This PR removes the fallback mechanism from the Anthropic model context window detection as requested by the user. 
- Removed hardcoded fallback constants for model context window sizes
- Updated the initializeModelContextWindow method to throw errors instead of returning undefined
- Updated the tokenUsageFromMessage function to throw an error if the context window size is not available
- Changed the error handling in the constructor to better inform about initialization failures
This PR is an enhancement to PR #343 which implements the basic dynamic context window detection. This PR specifically removes the fallback mechanism as requested in the user feedback.
Relates to #342
> Refactor: Remove fallbacks from Anthropic context window detection

- packages/agent/CHANGELOG.md
- packages/agent/package.json
- packages/agent/src/core/llm/providers/anthropic.ts
> feat: implement dynamic context window detection for Anthropic models

- mycoder.config.js
- packages/agent/src/tools/getTools.ts
- packages/cli/src/commands/$default.ts
- packages/cli/src/commands/tools.ts
- packages/cli/src/options.ts
- packages/cli/src/settings/config.ts
- packages/docs/docs/usage/configuration.md
- packages/docs/docs/usage/sub-agent-modes.md
This PR implements GitHub issue #344, adding support for different sub-agent workflow modes.
- Added a new configuration option `subAgentMode` with three possible values:
- `disabled`: No sub-agent tools are available (default)
- `sync`: Parent agent waits for sub-agent completion before continuing (experimental)
- `async`: Sub-agents run in the background (experimental)
- Updated the `getTools` function to conditionally include agent tools based on the configured mode
- Added CLI option support for the new configuration
- Created comprehensive documentation for the new feature in `sub-agent-modes.md`
- Updated the configuration documentation to include the new option
- Added a new documentation page explaining the different sub-agent workflow modes
- Updated the configuration …
> feat: implement sub-agent workflow modes (disabled, sync, async)

- packages/agent/src/tools/getTools.ts
- packages/agent/src/tools/think/index.ts
- packages/agent/src/tools/think/think.test.ts
- packages/agent/src/tools/think/think.ts
This PR adds a new `think` tool to the default set of tools in MyCoder. The think tool allows the agent to explicitly think through complex problems without taking any external actions. It serves as a way to document the agent's reasoning process and can improve problem-solving abilities.
- Added a new `think` tool in `packages/agent/src/tools/think/`
- Added the tool to the default set of tools in `getTools.ts`
- Implemented tests for the new tool
- All tests are passing
This implementation is based on the request in issue #351, which references research from Anthropic showing how a simple "think" tool can improve Claude's problem-solving skills.
Resolves #351
```javascript
await toolAgent.execute({
name: 'think',
parameters: {
thought: 'I need to consider all possible solutions before …
```
> Add think tool for complex reasoning

- .mycoder/ISSUE_TRIAGE.md
This PR addresses issue #356 by adding issue triage guidelines to be used by a GitHub workflow for automatic issue triage.
- Added `.mycoder/ISSUE_TRIAGE.md` with comprehensive guidelines for issue triage, including:
- Issue classification (Bug, Feature, Request)
- Label recommendations (bug, documentation, question, duplicate, enhancement, help wanted)
- Detailed triage process steps
- Guidelines for investigating different issue types
- Communication guidelines
A GitHub workflow needs to be created to use these guidelines. Due to permissions limitations, I can't create the workflow file directly, but here's the proposed workflow file content that should be added to `.github/workflows/issue-created.yml`:
```yaml
name: MyCoder Issue Triage Action
on:
issues:
types: [opened]
permissions: …
```
> Add issue triage guidelines

- .mycoder/PR_REVIEW.md
This PR addresses issue #350 by adding PR review guidelines.
- Added `.mycoder/PR_REVIEW.md` with comprehensive PR review guidelines
- The guidelines cover:
- Issue alignment
- Code quality
- Function and component design
- Testing
- Documentation
- Performance considerations
- Security considerations
- Accessibility
- Browser/environment compatibility
- Follow-up review guidelines
I also created a PR review GitHub Action workflow file (`.github/workflows/pr-review.yml`) based on the existing issue-comment.yml template, but I was unable to include it in this PR due to permission limitations:
```
! [remote rejected] feature/pr-review-action -> feature/pr-review-action (refusing to allow a GitHub App to create or update workflow `.github/workflows/pr-review.yml` without `workflows` …
```
> Add PR review guidelines

- docs/github-cli-usage.md
- packages/agent/src/tools/shell/shellExecute.test.ts
- packages/agent/src/tools/shell/shellExecute.ts
- packages/agent/src/tools/shell/shellStart.test.ts
- packages/agent/src/tools/shell/shellStart.ts
- test_content.txt
This PR fixes the issue where GitHub comments created by mycoder sometimes don't escape newlines properly, resulting in literal "\\n" strings in PR descriptions instead of actual line breaks.
1. Added preprocessing in both `shellExecute` and `shellStart` tools to convert literal `\n` strings to actual newlines before base64 encoding the content.
2. Added unit tests to verify this functionality.
3. Created documentation (`docs/github-cli-usage.md`) explaining the proper way to handle multiline content with GitHub CLI.
Fixes #365
- Added unit tests that verify literal `\n` strings are properly converted to actual newlines.
- Tested both `shellExecute` and `shellStart` functionality.
Added a new documentation file `docs/github-cli-usage.md` with best practices for using GitHub CLI with …
> Fix: Convert literal \n to actual newlines in GitHub CLI interactions

- packages/cli/README.md
- packages/cli/src/commands/$default.ts
- packages/cli/src/options.ts
Closes #383
This PR adds the ability to use both file input () and interactive prompts () together in the CLI. When both flags are provided, the content from the file is loaded first, and then the user is prompted for additional input. Both inputs are combined into a single context for the agent.
- Modified the handler in  to support both file and interactive inputs
- Updated the descriptions for the  and  options in 
- Updated the README.md to document the new capability with examples
- Verified that the code compiles successfully
- Verified that all tests pass
- Manual testing to ensure the feature works as expected
- Updated README.md with an example of using the combined mode
> Add support for combining file input and interactive prompts

- docs/tools/fetch.md
- packages/agent/src/tools/fetch/fetch.test.ts
- packages/agent/src/tools/fetch/fetch.ts
This PR improves error handling for HTTP 4xx errors in the fetch tool, particularly for 400 Bad Request and 429 Rate Limit Exceeded errors. It implements retry mechanisms with exponential backoff and adds a "slow mode" feature to help avoid rate limits.
- Added retry mechanism for 400 Bad Request errors with exponential backoff
- Implemented exponential backoff for 429 Rate Limit Exceeded errors
- Added support for the Retry-After header
- Added "slow mode" that can be enabled automatically after rate limit errors or manually
- Added comprehensive test suite for error handling scenarios
- Added documentation for the fetch tool with examples of the new error handling features
All tests pass, including the new error handling tests. The implementation has been verified to handle:
- Bad …
> Improve Error Handling for HTTP 4xx Errors
